language: scala
jdk:
- oraclejdk8
scala:
- 2.11.8
env:
  global:
  - secure: KODguqNSCpddCSKz0HmzwkXfwp8xUWZotog0bOW0oZDYu2YbO5QVPh49tXcbsJeW1PKd/C6Hyq+CzlvlOn6quKRfQOjLFKVth1qxlx4K3LEbyZ12nVDSlT5OxyK34JBAbdp2Cl7TrAuTDXWaF5b7tETGk3QC8OU26qlZ2dDgpjAWvKLHK6qa/bY/x56p2Yy1pm+ln/sH29dS4ZvDnXr309dYi2s3F+CldVJ7eajZe5Ca/vQVc8i22UuvuUVP2zWkBHQ3Hxq9HgnG3pdNGADGfo5glyf72LOKRmtn6jz9AHk7mg+4n4htSZjzNj/A/GMuE3kWwtAVCXxyW9o+MoLhMWkyWsIYjBbvvi40ZN1S2HdZ995C/iEw0hd6f2CAnmsietJ1ObCryk10YQ29hp2+4ZGXIRMsC5NDMtJehHKWNchrlfLWsA5sHZYeMfSFXxyH8U71O6HbQFZUaCV+XPAYjv9cF2xBnfFSzQeUgvBH9oLWlmPdZOffkmQmxk7ywi9NDa/OBh8P9rt6oL3jPiAeoLcutV0QJw8UrAQid8XeYZjIopOsz3CWfv1hFOSx7//XIcDitflGA8GAFu2exxt8Qj40r3y3HgiJbR0YWATlSb0z43Moxga+5WiPguq9Zd/4YaI9ZAGOb0G8d2mxcrbvHwJZcZWdpA2gu33SS6GiKs0=
  - secure: QRipEFNqarjEab9ptxKpZuw8VNqjLHYSuDsrGh0Z3ymz6HnUqYkaBtrPmZNPopD3tuEraDzcbhrcnSkspnWH334MFrZUrzZJnYWV6wlZ+O8W8m/xwIRUtp7Jvj5nmzVbyp8u5YnpyGB40OdhsoGLopNOyL8Me5xLsghH0kVdouGZsmYMVCh6gEWTjJgXuBHxTwRyj6MOnEI/eFT6FNcqI1JDO0CCdKUVrQlxPnNG5Ui+/J5QcZ6fojWPF5CFMxA2zp1fj2OrWsfiiGstNWSrhocnxNWG7bkBAlgEI54nWG8dJDBMiQHD4fNk2QGAy31S+xW6qXA+rXwWpXHGQWFoPv9L+EW1O447/WItzMs1AXylS/QJTd7Y3dM14i8JtqLXLlJp6/kFPoNBkbH8L5lAIkf+rkcUy+LzDaF+Fw29aWMrbLeDdwtDPLDX5dMqx2DzNwOy38WQC1uI3QX9bxahKIr+ZfItjzieTXj9If5uu8dsmGjZUgrwQEu+L6brR3GrawA4BrFVcvl08x00fBCV1vnkUG9MCYkzqM/r3jwNPZTbqiH0OhYkzbmxjPRruoXbQXXcAom8ia01NqEMIVJqkVjFoWnx1UpX27+ju4YA/XxLawkq9Sssor3xw6nnugFQK4NoYmptOpQI5vMsmA9Jla1cJtjM3Gz1fBRbzA5VXOg=

after_success:
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && { sbt publish; };"


  